"""baseline

Το πλήρες σχήμα ΟΠΩΣ ήταν πριν το Alembic (δημιουργήθηκε προηγουμένως από
db.create_all() + το χειροκίνητο auto-migration _add_missing_columns στο
app.py). Από εδώ και πέρα, ΚΑΘΕ αλλαγή σχήματος γίνεται με νέο migration
(`alembic revision --autogenerate -m "..."`), όχι με το παλιό μηχανισμό.

Revision ID: 0001
Revises:
Create Date: 2026-08-07 20:05:04.627683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workshops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('subscription_status', sa.String(length=20), nullable=False),
    sa.Column('business_type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('terms_accepted_at', sa.DateTime(), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workshop_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('plate', sa.String(length=20), nullable=False),
    sa.Column('vat', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('vehicle_category', sa.String(length=50), nullable=True),
    sa.Column('vehicle_factory', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workshop_id', 'plate', name='uq_customer_workshop_plate')
    )
    op.create_index(op.f('ix_customers_workshop_id'), 'customers', ['workshop_id'], unique=False)
    op.create_table('dcl_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workshop_id', sa.Integer(), nullable=False),
    sa.Column('id_dcl', sa.String(length=50), nullable=True),
    sa.Column('plate', sa.String(length=20), nullable=False),
    sa.Column('branch', sa.Integer(), nullable=False),
    sa.Column('client_service_type', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.String(length=20), nullable=False),
    sa.Column('provided_service_category', sa.Integer(), nullable=True),
    sa.Column('provided_service_category_other', sa.String(length=255), nullable=True),
    sa.Column('vehicle_movement_purpose', sa.Integer(), nullable=True),
    sa.Column('is_diff_pickup_location', sa.Boolean(), nullable=True),
    sa.Column('vehicle_pickup_location', sa.String(length=250), nullable=True),
    sa.Column('is_diff_return_location', sa.Boolean(), nullable=True),
    sa.Column('vehicle_return_location', sa.String(length=250), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('rental_expected_days', sa.Integer(), nullable=True),
    sa.Column('expected_return_at', sa.DateTime(), nullable=True),
    sa.Column('entry_completion', sa.Boolean(), nullable=False),
    sa.Column('invoice_kind', sa.Integer(), nullable=True),
    sa.Column('reason_non_issue_type', sa.Integer(), nullable=True),
    sa.Column('creation_date_time', sa.DateTime(), nullable=True),
    sa.Column('completion_date_time', sa.DateTime(), nullable=True),
    sa.Column('mark', sa.String(length=50), nullable=True),
    sa.Column('correlate_id', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('aade_state', sa.String(length=20), nullable=True),
    sa.Column('aade_pending_method', sa.String(length=20), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dcl_entries_workshop_id'), 'dcl_entries', ['workshop_id'], unique=False)
    op.create_table('fleet_vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workshop_id', sa.Integer(), nullable=False),
    sa.Column('plate', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workshop_id', 'plate', name='uq_fleet_workshop_plate')
    )
    op.create_index(op.f('ix_fleet_vehicles_workshop_id'), 'fleet_vehicles', ['workshop_id'], unique=False)
    op.create_table('ocr_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workshop_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('engine', sa.String(length=30), nullable=False),
    sa.Column('ocr_plate', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('warnings_count', sa.Integer(), nullable=False),
    sa.Column('parser_corrected', sa.Boolean(), nullable=False),
    sa.Column('final_plate', sa.String(length=20), nullable=True),
    sa.Column('user_edited', sa.Boolean(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ocr_metrics_workshop_id'), 'ocr_metrics', ['workshop_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workshop_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_workshop_id'), 'password_reset_tokens', ['workshop_id'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workshop_id', sa.Integer(), nullable=False),
    sa.Column('aade_username', sa.String(length=255), nullable=True),
    sa.Column('aade_subscription_key', sa.String(length=512), nullable=True),
    sa.Column('branch', sa.Integer(), nullable=False),
    sa.Column('entity_vat_number', sa.String(length=20), nullable=True),
    sa.Column('installation_id', sa.String(length=32), nullable=True),
    sa.Column('force_real_aade', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_workshop_id'), 'settings', ['workshop_id'], unique=True)
    op.create_table('aade_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dcl_entry_id', sa.Integer(), nullable=True),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('request_json', sa.Text(), nullable=True),
    sa.Column('response_json', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dcl_entry_id'], ['dcl_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aade_logs')
    op.drop_index(op.f('ix_settings_workshop_id'), table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_password_reset_tokens_workshop_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_ocr_metrics_workshop_id'), table_name='ocr_metrics')
    op.drop_table('ocr_metrics')
    op.drop_index(op.f('ix_fleet_vehicles_workshop_id'), table_name='fleet_vehicles')
    op.drop_table('fleet_vehicles')
    op.drop_index(op.f('ix_dcl_entries_workshop_id'), table_name='dcl_entries')
    op.drop_table('dcl_entries')
    op.drop_index(op.f('ix_customers_workshop_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_table('workshops')
    # ### end Alembic commands ###
